# Generated by Django 5.2.6 on 2025-09-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('fecha_nacimiento', models.CharField(max_length=10, verbose_name='Fecha de nacimiento')),
                ('ultimos_digitos_tarjeta', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos de la tarjeta')),
                ('saldo', models.CharField(max_length=20, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
